### ISSUE TITLE
Max button on debt payback

### ISSUE THREAD

**Issue by xadcv** [ebtc-protocol/ebtc-bugs-and-issues#2]
**Is your feature request related to a problem? Please describe.**
Clearing debt should be possible without having to check the number of decimals left in a position.

**Describe the solution you'd like**
Just requires a 'Max' button on the input field for eBTC debt to select the balanceOf eBTC tokens

**Describe alternatives you've considered**
Leaving it up to the user and hiding everything past 2 decimal places will leave dust on people's wallets

![image](https://github.com/ebtc-protocol/ebtc-bugs-and-issues/assets/343821/3c945f7f-3d2d-4707-b79d-48a2065d961f)

**Comment by mrbasado** [comment]
@xadcv Thank you for your feedback! we have added max buttons on Debt->Pay back and Collateral->Withdraw.
