### ISSUE TITLE
BorrowMore dialog is showing new and old positions that are same. After confirming, BorrowOperations error will show up.

### ISSUE THREAD

**Issue by richardzheng8829** [ebtc-protocol/ebtc-bugs-and-issues#9]
**Describe the bug**
After clicking BorrowMore button, dialog will show new and old positions that are same. After confirming, BorrowOperations error will show up.

**To Reproduce**
1. Go to 'Manage Position'
2. Click on 'Borrow More'
3. Click on 'Confirm' button

**Expected behavior**
`Borrrow More` should suggest new borrowing position based onb borrowing power available to me.
`Confim` button should be disabled if new and old positions are same.

**Screenshots**
![BorrowMore](https://github.com/ebtc-protocol/ebtc-bugs-and-issues/assets/144299680/dbc93105-691e-468a-b4d9-1eba7333eadc)
![BorrowOperations_error](https://github.com/ebtc-protocol/ebtc-bugs-and-issues/assets/144299680/54d899df-9fec-47fe-a729-3644cb9331a5)

 - Windows 10
 - Chrome 119

**Comment by mrbasado** [comment]
@richardzheng8829 thanks for the feedback. apologies for the late reply but a fix has been put in for this
